version: "3.9"
services:
  spring-api-image:
    image: spring-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    networks:
        - spring-api-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: 1998
      MYSQL_DATABASE: eldar
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
        - "3306:3306"
    networks:
        - spring-api-network
    volumes:
      - mysql-data:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql-volume: