spring:
  application:
    name: challenge-eldar-senior
  profiles:
    active: local
---
# LOCAL
server:
  port: 9000
  servlet:
    context-path: /api/v1/eldar
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/eldar
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
application:
  name: challenge-eldar
  version: 0.1.0
  developer: caito Vilas
  limit-Minimum-Stock: 2
  email: ${EMAIL}
  email-pass: ${EMAIL_PASS}

---
# UAT
server:
  port: 9000
  servlet:
    context-path: /api/v1/eldar
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    url: jdbc:mysql://localhost:3306/eldar
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
application:
  name: challenge-eldar
  version: 0.1.0
  developer: caito Vilas
  imit-Minimum-Stock: 2
  email: ${EMAIL}
  email-pass: ${EMAIL_PASS}
